# Generated by Django 4.1.5 on 2023-01-09 15:57

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapiapp', '0002_alter_postphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(default='account_photos/default.jpg', unique=True, upload_to='account_photos')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_photos', to='coreapiapp.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
