# Generated by Django 4.1.5 on 2023-01-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapiapp', '0003_accountphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountphoto',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_photo', to='coreapiapp.account'),
        ),
    ]
