version: '3.9'

volumes:
  postgres_data:
  app_data_static:
  app_data_cache:
  app_data_media:
  app_data_pip_cache:
services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: apigram_development
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready", "-Upostgres", "-dapigram_development"]
  app:
    build: .
    command: uwsgi --ini uwsgi.ini
    links:
      - 'db'
    restart: always
    ports:
      - 8000:8000
    volumes:
      - app_data_static:/usr/src/app/apigram/static
      - app_data_media:/usr/src/app/apigram/media
      - app_data_cache:/root/.cache
      - app_data_pip_cache:/tmp/cache
    environment:
      - DJANGO_SETTINGS_MODULE=apigram.settings.docker

  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - app_data_static:/usr/src/app/apigram/static:ro
      - app_data_media:/usr/src/app/apigram/media:ro
    ports:
      - "443:8000"
    links:
      - app
    
