version: '3.9'

volumes:
  postgres_data:
  app_data_static:
  app_data_cache:
  app_data_media:
  app_data_pip_cache:
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: apigram_development
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-Upostgres",
          "-dapigram_development"
        ]
  app:
    platform: linux/amd64
    build: .
    image: georgezhukov/apigram:latest
    command: uwsgi --ini uwsgi.ini
    environment:
      - DJANGO_SETTINGS_MODULE=apigram.settings.docker
      - DJANGO_STATIC_ROOT=/app/static
      - DJANGO_MEDIA_ROOT=/app/media
    
    restart: always
    volumes:
      - app_data_static:/app/static
      - app_data_media:/app/media


    depends_on:
      - db

    healthcheck:
      test: curl --silent --fail https://apigram.crabdance.com/api/v1/ || exit 1

  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
      - app_data_static:/usr/src/app/apigram/static:ro
      - app_data_media:/usr/src/app/apigram/media:ro
    links:
      - app
    depends_on:
      - app
    healthcheck:
      test: service nginx status || exit 1
