version: '3.9'

volumes:
  postgres_data:
  app_data:
services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: apigram_development
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready", "-Upostgres", "-dapigram_development"]
  app:
    build: .
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    links:
      - 'db'
    restart: always
    ports:
      - 8000:8000
    volumes:
      - app_data:/usr/src/app/apigram
    environment:
      - DJANGO_SETTINGS_MODULE=apigram.settings.docker

  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - app_data:/usr/src/app/apigram:ro
    ports:
      - "443:8000"
    links:
      - app
    
