# Generated by Django 4.1.5 on 2023-01-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password_hash',
        ),
        migrations.DeleteModel(
            name='AccountToken',
        ),
    ]
