# Generated by Django 4.1.5 on 2023-01-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_remove_account_email_remove_account_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='coreapi.post'),
        ),
    ]
