# Generated by Django 4.1.5 on 2023-01-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='coreapi.post'),
        ),
    ]
