# Generated by Django 4.1.5 on 2023-01-05 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0005_alter_postphoto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(max_length=1048576, unique=True, upload_to='post_photos', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
